// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: audit_logs.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (actor_user_id, action, entity, metadata, ip, user_agent)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, actor_user_id, action, entity, metadata, ip, user_agent, created_at
`

// CreateAuditLogParams holds the parameters for the CreateAuditLog query.
type CreateAuditLogParams struct {
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	Action      string      `json:"action"`
	Entity      string      `json:"entity"`
	Metadata    []byte      `json:"metadata"`
	Ip          pgtype.Text `json:"ip"`
	UserAgent   pgtype.Text `json:"user_agent"`
}

// CreateAuditLog inserts a new audit log entry.
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ActorUserID,
		arg.Action,
		arg.Entity,
		arg.Metadata,
		arg.Ip,
		arg.UserAgent,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.Action,
		&i.Entity,
		&i.Metadata,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditLogsByUser = `-- name: GetAuditLogsByUser :many
SELECT id, actor_user_id, action, entity, metadata, ip, user_agent, created_at
FROM audit_logs
WHERE actor_user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

// GetAuditLogsByUserParams holds the parameters for the GetAuditLogsByUser query.
type GetAuditLogsByUserParams struct {
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

// GetAuditLogsByUser returns paginated audit log entries for a given user.
func (q *Queries) GetAuditLogsByUser(ctx context.Context, arg GetAuditLogsByUserParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getAuditLogsByUser, arg.ActorUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.Entity,
			&i.Metadata,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
