// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
)

// DBTX is the interface satisfied by both *pgx.Conn and *pgxpool.Pool.
type DBTX interface {
	Exec(context.Context, string, ...any) (pgconn.CommandTag, error)
	Query(context.Context, string, ...any) (pgx.Rows, error)
	QueryRow(context.Context, string, ...any) pgx.Row
}

// New creates a Queries instance backed by the provided DBTX.
func New(db DBTX) *Queries {
	return &Queries{db: db}
}

// Queries holds the database handle used by all generated query methods.
type Queries struct {
	db DBTX
}

// WithTx returns a new Queries that executes within the provided transaction.
func (q *Queries) WithTx(tx pgx.Tx) *Queries {
	return &Queries{db: tx}
}

// WithPool returns a new Queries backed by the provided pool.
func WithPool(pool *pgxpool.Pool) *Queries {
	return &Queries{db: pool}
}
