// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// User represents a row in the users table.
type User struct {
	ID        pgtype.UUID        `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	Verified  bool               `json:"verified"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// AuditLog represents a row in the audit_logs table.
type AuditLog struct {
	ID          pgtype.UUID        `json:"id"`
	ActorUserID pgtype.UUID        `json:"actor_user_id"`
	Action      string             `json:"action"`
	Entity      string             `json:"entity"`
	Metadata    []byte             `json:"metadata"`
	Ip          pgtype.Text        `json:"ip"`
	UserAgent   pgtype.Text        `json:"user_agent"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
